AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: encatch IMS - FastAPI on AWS Lambda

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 1024
    Architectures: [x86_64]
    Environment:
      Variables:
        DB_URL: "sqlite:///./ims.db"  # replace with RDS URL later

Resources:
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowMethods: ['*']
        AllowOrigins: ['*']

  ImsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      CodeUri: ../
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
      Policies:
        - AWSLambdaBasicExecutionRole
